### ISSUE TITLE
Integrate capsolver.com

### ISSUE THREAD

**Issue by Xeeeno** [Mirio/captcha2upload#5]
Hey, it's possible that you integrate [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by Mirio** [comment]
Hey @Xeeeno,
Sorry but this repo is not more developed.
I can suggest to you check on PyPI if another library exists.
Regards,
